### ISSUE TITLE
Validate certificate exception

### ISSUE THREAD

**Issue by DmitryGaluschkin** [lsnepomuceno/laravel-a1-pdf-sign#101]
**Describe the bug**
Exception during validation the signed document

**To Reproduce**
Create some pdf and sign with .pfx cert.
After that I am trying to check if PDF is valid, but I have an exception:
Undefined array key 1

1. Create cert file 
   $cert = new ManageCert;
   $cert->fromPfx('path/to/certificate.pfx', 'password');     
2. Download it to some storage
   $pdf = new SignaturePdf('path/to/pdf/file.pdf', $cert, SignaturePdf::MODE_DOWNLOAD)
   return $pdf->signature();
3. Check if PDF valid 
   dd(ValidatePdfSignature::from('path/to/pdf/file.pdf');

**Expected behavior**
Dump data with the certificate

**Versions involved:**
- Laravel: 9.41
- PHP 8.1.17
- Laravel A1 Pdf Sign 1.0
- Composer 2.1

**Additional context**
Firstly I thought that I have a wrong cert data, but when I checked with another PDF signed with 
mobile APP I have the same error. 
As I see exception appeared in function
convertPlainTextToObject Line:111

**Comment by lsnepomuceno** [comment]
Hello @DmitryGaluschkin ,

Could you provide a more detailed capture of the error or, if possible, send me the signed file?

I performed several tests and did not identify any problems in validating the signatures.
