### ISSUE TITLE
Windows env can not find openssl command

### ISSUE THREAD

**Issue by kanokith** [lsnepomuceno/laravel-a1-pdf-sign#102]
**Describe the bug**
My pc can not read certificate from file (Windows 11). But it works well on my Linux server. 

![2023-05-18 08_53_41 - PDF_-_Google_Chrome](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/assets/41558046/0b27c709-068a-4edb-af69-121345371480)

I use an example code on the doc.

>         try {
>             $cert = new ManageCert;
>             $cert->setPreservePfx() // If you need to preserve the PFX certificate file
>                  ->fromPfx($path, $password);
>             dd($cert->getCert());
>         } catch (\Throwable $th) {
>             dd($th);
>         }

**What I do**
1. Looking similar issues and found this https://github.com/lsnepomuceno/laravel-a1-pdf-sign/issues/71

2. Update openssl on my windows, it work correctly.
![2023-05-18 09_24_54 - Command_Prompt](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/assets/41558046/a4f6ddb7-759f-4b22-b96b-f434d8941d9d)

3. Check is openssl extension enable.
![2023-05-18 08_53_15 - PDF_-_Google_Chrome](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/assets/41558046/ec8411c4-814e-4397-a46e-5c0df18ccd88)

4. I try others command like php --version, composere --version from Process::fromShellCommandline($command); 
Got the same error "Process runtime error, reason: "'php, composer' is not recognized as an internal or external command,. . operable program or batch file.. . ""

**Versions involved:**
- Laravel: 9.52
- Laravel A1 Pdf Sign 1.0
- Composer 2.5

**Comment by kanokith** [comment]
Update. 
PHP Function shell_exec work well with my PC. I can call open ssl from shell_exec command. I guess I have a problem with Class Symfony\Component\Process.

**Comment by kanokith** [comment]
It's work when I use this code

`        $command = 'openssl version';
        $process = Process::fromShellCommandline($command,null,[
            'PATH' => getenv("PATH")
          ]);
        $process->run();
`

![2023-05-18 13_02_36 - PDF_-_Google_Chrome](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/assets/41558046/7e100385-e486-42ad-bc20-c141033dd6be)

**Comment by lsnepomuceno** [comment]
Hello @kanokith ,

I ran some tests on Windows 10 and 11 and had no problems running the package or OpenSSL.

I will add the Windows environment in the test pipeline to try to catch possible problems.

Once it's done, I'll update this issue with the results.

**Comment by lsnepomuceno** [comment]
I carried out several tests trying to simulate the case described in the issue, but I was unable to reproduce the problem.

In Windows environments (10 and 11) with OpenSSL installed and running, the application occurred normally and it was possible to sign documents using this package.

Therefore, I will consider this case as a problem in your environment since we do not have new cases and in all tests the signature occurred normally.
