### ISSUE TITLE
Wrong location of temp directory

### ISSUE THREAD

**Issue by oliworx** [lsnepomuceno/laravel-a1-pdf-sign#107]
**Describe the bug**

Running my projects unit tests on a GitLab CI pipeline the following error occurs:

_LSNepomuceno\LaravelA1PdfSign\Exception\ProcessRunTimeException: Process runtime error, reason: "pkcs12: Can't open "/my-project/vendor/lsnepomuceno/laravel-a1-pdf-sign/src/Temp/99b32999-6a57-418e-a2a0-0c289acc60bc.crt" for writing, Permission denied. "_

**Expected behavior**
Vendor folder must never be written on runtime.

Instead Laravel's `storage_path` should be used or `sys_get_temp_dir`.

**Versions involved:**
- Laravel: 8.
- Laravel A1 Pdf Sign 0.0.18
- Composer 2.5.5

**Additional information**
This is caused by the line  
```$tempDir = __DIR__ . '/Temp/';```   
in the `a1TempDir` helper function

**Comment by lsnepomuceno** [comment]
Hello @oliworx ,

It's a great suggestion, I'm finalizing some tweaks in the package and in the next version that will be released on August 4th, the option to change the directory will be implemented.
