### ISSUE TITLE
Não consigo instalar

### ISSUE THREAD

**Issue by darkwolf1812** [lsnepomuceno/laravel-a1-pdf-sign#146]
Boa noite.
Tenho o intervention/image-laravel instalado na versão ^1.2
Quando eu tento instalar com o composer, me dá os seguintes erros:

Problem 1
    - lsnepomuceno/laravel-a1-pdf-sign[0.0.1, ..., 0.0.18] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - lsnepomuceno/laravel-a1-pdf-sign[1.0.4, ..., 1.0.5] require illuminate/support ^9 -> found illuminate/support[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - lsnepomuceno/laravel-a1-pdf-sign[1.0.6, ..., 1.0.11] require illuminate/support ^9 || ^10 -> found illuminate/support[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.12] but these were not loaded, likely because it conflicts with another require.
    - lsnepomuceno/laravel-a1-pdf-sign[1.1.0, ..., 1.1.2] require intervention/image ^2.7 -> found intervention/image[2.7.0, 2.7.1, 2.7.2] but the package is fixed to 3.7.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires lsnepomuceno/laravel-a1-pdf-sign * -> satisfiable by lsnepomuceno/laravel-a1-pdf-sign[0.0.1, ..., 0.0.18, 1.0.4, ..., 1.1.2].

Estou usando a versão 11 do Laravel.
O que posso fazer?

Obrigado.

**Comment by lsnepomuceno** [comment]
Bom dia @darkwolf1812 ,

Para instalação correta no Laravel 11 é necessário que todas as dependências estejam na última versão, conforme descrito no composer.json.
Para te auxiliar, recomendo que atualize sua versão do intervention/image para ^2.7.
Você pode visualizar as dependências dessa versão do intervention/image através da página do packagist: https://packagist.org/packages/intervention/image#2.7.0

Segue abaixo requisito do pacote de assinaturas para a versão 11 do Laravel.
![image](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/assets/14093492/dc03ddd6-c808-42b5-802e-715eb00521ff)
