### ISSUE TITLE
Não instala com a versão 3.7.2 do intervention/image

### ISSUE THREAD

**Issue by darkwolf1812** [lsnepomuceno/laravel-a1-pdf-sign#155]
Estou tentando instalar, mas tenho a versão 3.7.2 do intervention instalada. Me dá o seguinte erro:

- lsnepomuceno/laravel-a1-pdf-sign[1.1.0, ..., 1.2.0] require intervention/image ^2.7 -> found intervention/image[2.7.0, 2.7.1, 2.7.2] but it conflicts with your root composer.json require (^3.7).

Consegue alterar a versão para uma mais nova?

Obrigado.

**Comment by lsnepomuceno** [comment]
Olá @darkwolf1812 ,

Estou providenciando a atualização da dependência do intervention.

**Comment by darkwolf1812** [comment]
Opa.. Top.. Muito obrigado. No aguardo.

**Comment by lsnepomuceno** [comment]
Versão contendo suporte para intervention/image 3.8 liberada, basta utilizar a tag ^1.3: https://github.com/lsnepomuceno/laravel-a1-pdf-sign/releases/tag/1.3.0

**Comment by darkwolf1812** [comment]
Perfeito.. Muito obrigado !!
