### ISSUE TITLE
Enable Multiple Signatures in PDF Without Replacing Existing Signatures

### ISSUE THREAD

**Issue by FuriosoJack** [lsnepomuceno/laravel-a1-pdf-sign#159]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when I need to have multiple signatures on a document, and the tool replaces the existing signatures instead of allowing all signers to coexist in the PDF.

**Does your tool support adding multiple signatures?**  
Can your tool accommodate multiple signers on the same document without replacing previous signatures? It’s crucial for situations where two or three individuals need to sign the same PDF, ensuring that all signatures are retained.

**Describe the solution you'd like**  
I would like to know if your tool currently has the capability to support multiple signatures on a single PDF. If this feature is not available, I would be happy to help and contribute code if necessary to implement this functionality.

**Describe alternatives you've considered**  

**Additional context**  

**Versions involved:**  
- Laravel: [e.g. 9.21]  
- Laravel A1 Pdf Sign: [e.g. 0.0.18]  
- Composer: [e.g. 2.1]

**Comment by lsnepomuceno** [comment]
Thank you for reaching out and for your feature request.

Our tool currently relies on the dependency tecnickcom/TCPDF, which provides the PDF signing capabilities. At the moment, TCPDF does not natively support multiple signatures in a single PDF document. This means that adding a second signature would overwrite the existing one, which is causing the issue you've encountered.

However, we have already submitted a support request to the developer of TCPDF regarding the implementation of Long Term Validation (LTV), which includes support for multiple signatures. We're hoping that this will be addressed in a future release.

In the meantime, if you're familiar with PDF signing and would like to contribute code to support multiple signers, we would greatly appreciate your help in improving this functionality.

Thank you for your understanding, and feel free to reach out if you have further questions or ideas!

References:
https://github.com/lsnepomuceno/laravel-a1-pdf-sign/issues/29
https://github.com/tecnickcom/TCPDF/issues/430
https://github.com/tecnickcom/tc-lib-pdf/issues/115
https://github.com/tecnickcom/TCPDF/issues/191

**Comment by FuriosoJack** [comment]
Obrigado por responder tão rapidamente. Sou da Colômbia e estava usando sua ferramenta, aliás muito boa.

Porém, esse inconveniente de múltiplas assinaturas, depois do que você me contou, verifiquei outra biblioteca e acho que vou passar da sua para esta outra, onde fiz alguns testes e resolve esse problema. https://github.com/dealfonso/sapp/

De qualquer forma, muito obrigado, talvez em outro momento o código possa ser refatorado para parar de usar a dependência tdpdf e usar esta biblioteca neste pacote Laravel.

Tchau, saudações e obrigado pela atenção.

**Comment by lsnepomuceno** [comment]
Olá @FuriosoJack ,

Tenho conhecimento do pacote: https://github.com/dealfonso/sapp/
Existem planos para uso dele na próxima do meu pacote para o Laravel, estou validando alguns pontos necessários para implementar a funcionalidade.
