### ISSUE TITLE
Defining the pdf name

### ISSUE THREAD

**Issue by ALGAzevedo** [lsnepomuceno/laravel-a1-pdf-sign#16]
Would be nice to be able to set the PDF name to one that we want instead the UUID. Is is possible to add this feature? Or define it as the name of the readed pdf and concatenate something like "_signed". This would help a lot. Thanks

**Comment by lsnepomuceno** [comment]
hello @ALGAzevedo ,

The next update will include the option for the file to be generated with the original name along with the suffix "_signed".

**Comment by ALGAzevedo** [comment]
Thank you! That will help a lot.

**Comment by lsnepomuceno** [comment]
Hello @ALGAzevedo,

We continue to implement functionality in PR #19, ensuring that all features from previous versions are compatible.

Thanks for the suggestion, the functionality will be available in version 0.0.10.
