### ISSUE TITLE
PFX file disappears

### ISSUE THREAD

**Issue by ALGAzevedo** [lsnepomuceno/laravel-a1-pdf-sign#17]
Everytime i use the PFX file it disappears, is there something we can do about it?

**Comment by ALGAzevedo** [comment]
Ok, i solve this using a Process to generate the PFX every time with the crt and key. Doesnt make much sense since you are going to make a crt from the pfx. We should be able to use both pfx or crt. 👍

**Comment by lsnepomuceno** [comment]
Hello @ALGAzevedo ,

For security reasons we do not recommend storing the certificate explicitly on the server.

For a better use of the package, it is recommended that the data be stored encrypted in the database.

Just look at this topic on the Wiki:
[Store certificate data securely in the database.](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/wiki/Usage%3A-1%29--Working-with-certificate#4---store-certificate-data-securely-in-the-database)
