### ISSUE TITLE
fromPfx method does not fail on e.g. wrong password

### ISSUE THREAD

**Issue by rabol** [lsnepomuceno/laravel-a1-pdf-sign#23]
The method fromPFX() does not fail or throw any error in case the provided password is wrong

```
try {
      $process = Process::fromShellCommandline($openssl);
      $process->run();

      while ($process->isRunning());

      $process->stop(1);
    } catch (ProcessFailedException $exception) {
      throw $exception;
    }
``` 

should check the $process->isSuccessful() and if not, then throw an error

e.g. in case og wrong password, the isSucessful() is one and $process->getErrorOutput() will say: Mac verify error: invalid password?

**Comment by lsnepomuceno** [comment]
Hello @rabol,

Thanks for identifying the issue, we will include the fix in the next 0.0.12 update.
