### ISSUE TITLE
Consider adding a getter on SignaturePdf

### ISSUE THREAD

**Issue by rabol** [lsnepomuceno/laravel-a1-pdf-sign#25]
Please consider to make a getter for the $pdf on the SignaturePdf class, so that it is possible to add extra properties while signing.

**Comment by lsnepomuceno** [comment]
Hi @rabol,

Could you detail your need?

If possible, describe an example.

**Comment by rabol** [comment]
Something like Author, tittle etc and metadata for the signature - there is a todo in the class SignaturePdf regarding $info 😀

currently the $pdf is declared as private so a getter would be nice
