### ISSUE TITLE
LTV signature

### ISSUE THREAD

**Issue by billsoftltd** [lsnepomuceno/laravel-a1-pdf-sign#29]
Hi,

How add LTV signature (long term validation)?

**Comment by lsnepomuceno** [comment]
Hi @billsoftltd,

Currently the package only allows the use of a single signature as there is this limitation in the @tcpdf package, as you can see in the links below.

- https://github.com/tecnickcom/TCPDF/issues/430
- https://github.com/tecnickcom/TCPDF/issues/191
- https://stackoverflow.com/questions/51209229/is-this-pdf-digital-signed-correctly-php-tcpdf

We are working to implement the feature in future updates.
