### ISSUE TITLE
is there any way to insert only text? in the same way that an image is inserted

### ISSUE THREAD

**Issue by edwinmacalopu** [lsnepomuceno/laravel-a1-pdf-sign#31]
reference image, only text is inserted.
![image](https://user-images.githubusercontent.com/15043775/148166371-734ca52e-c5f5-4569-ae51-02a1abaceb7a.png)

**Comment by lsnepomuceno** [comment]
Hello @edwinmacalopu, 

You can generate an image containing the desired text as an example of the method ["SealImage::fromCert"](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/blob/main/src/SealImage.php#L61), after generating the image just add it to the document, [Doc. Ref.](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/wiki/Usage%3A-2%29-Sign-PDF-File#3---sign-pdf-with-image-insertion).

Plain text is not natively possible in the library as it violates the basics of PDF documents.
