### ISSUE TITLE
Version alpha installation with psr-4 non compliant classes skipped ?

### ISSUE THREAD

**Issue by dgillier** [lsnepomuceno/laravel-a1-pdf-sign#44]
Hello,

I'm trying to install the last version (1.0.0) as I'm using Laravel 9.11 and PHP 8.1.
I got the following msgs after `composer require lsnepomuceno/laravel-a1-pdf-sign "^1"`.

`Class LSNepomuceno\LaravelA1PdfSign\Exceptions\InvalidX509PrivateKeyException located in ./vendor/lsnepomuceno/laravel-a1-pdf-sign/src/Exceptions/Invalidx509PrivateKeyException.php does not comply with psr-4 autoloading standard. Skipping.
Class LSNepomuceno\LaravelA1PdfSign\Exceptions\CertificateOutputNotFoundException located in ./vendor/lsnepomuceno/laravel-a1-pdf-sign/src/Exceptions/CertificateOutputNotFounfException.php does not comply with psr-4 autoloading standard. Skipping.`

Thanks, Denis

**Comment by lsnepomuceno** [comment]
Hi @dgillier,

I appreciate the feedback on the file naming issue.

I applied the fix to the files, just update their dependencies.

Link to the latest version: https://github.com/lsnepomuceno/laravel-a1-pdf-sign/releases/tag/1.0.1-alpha
