### ISSUE TITLE
PDF timestamping while signing ?

### ISSUE THREAD

**Issue by dgillier** [lsnepomuceno/laravel-a1-pdf-sign#45]
Thanks a lot for this library !

I wondering if you plan to add timestamping on it  (RFC3161) ?

(using for example https://www.freetsa.org/, or any secure timestamp server : https://kbpdfstudio.qoppa.com/list-of-timestamp-servers-for-signing-pdf/)

**Comment by lsnepomuceno** [comment]
Hi @dgillier,

The idea of ​​implementing RFC3161 was already in our plans.

I am finalizing the documentation of the new library and soon after I will start the studies and development of the TSA.

Thanks for the contribution.

**Comment by lsnepomuceno** [comment]
References for implementation:

- https://www.digistamp.com/technical/software-alternatives/using-openssl-to-request-timestamps
- https://www.freetsa.org/index_en.php#tap-tcp-2
- https://www.openssl.org/docs/man1.1.1/man1/openssl-ts.html#:~:text=DESCRIPTION,datum%20before%20a%20particular%20time.

**Comment by dgillier** [comment]
Another one  with code:
https://d-mueller.de/blog/dealing-with-trusted-timestamps-in-php-rfc-3161/

There is some functions in TCPDF to do it, but without implementation. 
Main question (for me) is how to embedded it in the PDF file:
Implemented  : `public function setTimeStamp($tsa_host='', $tsa_username='', $tsa_password='', $tsa_cert='')`
Not implemented : `protected function applyTSA($signature)`

**Comment by dgillier** [comment]
There is a patch for TCPDF to add timestamps to signature implementing the applyTSA function but looks a bit hacky to me...

https://github.com/tecnickcom/TCPDF/pull/243/commits/19f26a3a34f3556b4e525bf2add158129e49f899

**Comment by bilogic** [comment]
@dgillier did the patch work for you?

**Comment by dgillier** [comment]
Honestly, I did not try it...

**Comment by bilogic** [comment]
Ok, I tried the code and it does work. 

Just curious if you are familiar with the certificates, do you know if both below can be used to sign PDF?
I tried using a code signing cert to sign my PDF and it could not work.

https://sectigostore.com/secure-email-document-signing - $15/yr
https://sectigo.com/ssl-certificates-tls/document-signing-certificates - $299/yr

**Comment by dgillier** [comment]
You can have one for under $75

**Comment by bilogic** [comment]
@dgillier I was able to sign my PDF using another program with my code signing cert, however this code wasn't able to probably due to all the hardcoding.

I don't need to buy another cert :)

**Comment by lsnepomuceno** [comment]
Hello @dgillier ,

I'm finalizing the development of a new PDF package that will be responsible for the entire signature flow, manipulation and generation of PDF content, and the implementation of the TSA is already planned, therefore, I will close this ISSUE because it will not be treated in this package, but in the new one that can be viewed through the link: https://github.com/lsnepomuceno/php-pdf-processor
