### ISSUE TITLE
SealImage error

### ISSUE THREAD

**Issue by dgillier** [lsnepomuceno/laravel-a1-pdf-sign#46]
Hello,

I just tried to used your SealImage function (I'm using the 1.0 dev version for laravel 9 compatibility).

I'm having an error at 
`$image = SealImage::fromCert($cert);`

_Intervention \ Image \ Exception \ NotReadableException
Image source not readable_

I checked, the seal image is in the Vendor src/Resources/img/... 
My certificate is ok (works with SignaturePdf() )...
Any ideas of what's going on ?

Thanks, Denis

**Comment by lsnepomuceno** [comment]
Hello @dgillier,
We applied the directory reference fix in the SealImage class, we also included tests to make it easier to monitor for unexpected behavior.

You can find new features from [v1.0.2-alpha](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/tree/1.0.2-alpha) onwards.
