### ISSUE TITLE
Support for laravel version 6?

### ISSUE THREAD

**Issue by jw7712** [lsnepomuceno/laravel-a1-pdf-sign#51]
Is there a way to use this package in laravel 6?
I have a project in laravel 6 with some dependencies that keep me from updating the application to a newer version.

Thanks in advance.

**Comment by lsnepomuceno** [comment]
Hello @jw7712 ,

Thanks for the suggestion, but we currently have no plans to port the package to older versions of Laravel.

As you can see in the release note for version [0.0.12](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/releases/tag/0.0.12), there were changes in Laravel from version 8.56 that directly impact the development of the package, which makes compatibility with version 6 unfeasible.
