### ISSUE TITLE
How do I Verify the signed PDF?

### ISSUE THREAD

**Issue by erikwii** [lsnepomuceno/laravel-a1-pdf-sign#7]
Hey, this package is great, but how can I verify the signed pdf without adobe? Thanks in advance.

**Comment by lsnepomuceno** [comment]
Hi Erik,

First of all, I'm honored to be able to help you with this package.

There is an Openssl method that allows us to validate the certificates assigned in a file.

I will add it to the package and release it in version 0.0.6, I keep you informed.

See you soon!

**Comment by erikwii** [comment]
Hi Lucas,

I also have already seen the method.
It will be great if the feature is implemented in this package.

Can't wait for the update!

**Comment by lsnepomuceno** [comment]
[Release 0.0.6](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/releases/tag/0.0.6)

Good night @erikwii,

Version 0.0.6 released with signature validation feature.

Documentation also updated.
