### ISSUE TITLE
Openssl is not recognized

### ISSUE THREAD

**Issue by Guervyl** [lsnepomuceno/laravel-a1-pdf-sign#71]
**Describe the bug**
I got the error `Process runtime error, reason: "'openssl' is not recognized as an internal or external command,. . operable program or batch file.. . "`

**To Reproduce**
I have this simple code :
```
$app = new Container();
 $app->singleton('app', Container::class);
$app->singleton('files', fn () => new Filesystem);
Facade::setFacadeApplication($app);

$cert = new ManageCert();
$cert->fromPfx('C:/wamp64/www/facturacion electronica/WALTER ANDRES GARAY LUZURIAGA 090322112505.pfx', 'True22');

$pdf = new SignaturePdf('C:/wamp64/www/firma-doc/0202202301131234612300110010030000000013437950515.pdf', $cert, SignaturePdf::MODE_RESOURCE); // Resource mode is default
$resource = $pdf->signature();
```

**Expected behavior**
It was supposed to work.

**Screenshots**

**Versions involved:**
- Not using laravel

**Comment by Guervyl** [comment]
I have openssl installed on my windows 11 system.

Running the command in cmd:
`openssl pkcs12 -in C:/wamp64/www/facturacion electronica/WALTER ANDRES GARAY LUZURIAGA 090322112505.pfx -out C:\wamp64\www\firma-doc\vendor\lsnepomuceno\laravel-a1-pdf-sign\src/Temp/9866c6ae-de29-4bd7-bf34-76f841ecb24a.crt -nodes -password pass:Truepeak2022`

Output: `pkcs12: Use -help for summary.`

Looks like this library is deprecated.

**Comment by lsnepomuceno** [comment]
Hello @Guervyl ,

The error reported is that the openssl extension was not found on your server and has nothing to do with the package.

Windows openssl is not connected directly to xampp openssl or another web server, it is necessary that the dependencies are installed and enabled on your server.

Please validate if the extension is enabled on your web server as shown below:

* https://stackoverflow.com/a/11040496
* https://www.geeksforgeeks.org/how-to-enable-phps-openssl-extension-to-install-composer/
* https://arjunphp.com/how-to-enable-the-openssl-in-xampp/

Another piece of information is that this package and openssl are not deprecated.
