### ISSUE TITLE
Atualização para Laravel 10

### ISSUE THREAD

**Issue by emtudo** [lsnepomuceno/laravel-a1-pdf-sign#77]
Pelos meus testes funciona na versão php 8.2 sem alteração alguma.

E alterei o composer.json e o phpunit.xml e funcionou também para laravel 10.

Você pretende fazer a alteração? Posso fazer PR?

o phpunit.xml praticamente foi criado com o comando: vendor/bin/phpunit --migrate-configuration para funcioanr

O composer.json só adicionei as versões nova do laravel e pronto.

**Comment by lsnepomuceno** [comment]
Estou validando alguns pontos, pois irei depreciar o uso do symfony/process para dar uso do ProcessFacade do Laravel 10, como você pode ver no link:
https://laravel-news.com/process-facade-laravel-10

Como o Laravel 10 foi lançado hoje, imagino que até o final de semana eu já finalize os testes e suba uma nova versão.

**Comment by emtudo** [comment]
Eu já usei o progress do symfony, o laravel está apenas usando o mesmo fazendo um facade como vc mencionou, isso vc poderia lançar e depois fazer atualização pq não vai mudar nada para quem usa o pacote no final das contas.

**Comment by emtudo** [comment]
Na verdade eu até preferia que vc não usasses o facade do laravel rs

Pq ficaria mais simples portar o pacote para usar no symfony. Como seria bom se ele fosse mais agnóstico.

**Comment by lsnepomuceno** [comment]
Suporte ao Laravel 10 liberado a partir da versão [1.0.6](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/releases/tag/1.0.6).

A depreciação do symfony/process ocorrerá a partir da futura v2 deste pacote que terá suporte ao Laravel 11.
