### ISSUE TITLE
Parse error on certificate stored in DB

### ISSUE THREAD

**Issue by rabol** [lsnepomuceno/laravel-a1-pdf-sign#87]
**Describe the bug**
Retrieving certificate from DB returns an parse error:

**To Reproduce**
1. create certificate like this
$cert = new ManageCert();
        $cert->makeDebugCertificate();

        // For MySQL
        $uc = UserCertificate::create([
            'certificate' => $cert->encryptBase64BlobString($cert->getCert()->original),
            'password'    => $cert->getEncrypter()->encryptString('123456'),
            'hash'        => base64_encode($cert->getHashKey()), // IMPORTANT
            'user_id' => Str::uuid(),
            'name' => 'auto upload',
        ]);

2. get the certificate like this:
$uc = UserCertificate::find('98937f06-c230-466f-ba71-179b385d2cac');
dd($uc->parse()); 

parse method looks like this:

```
public function parse(): ?ManageCert
    {
        try {
            $hashKey = base64_decode($this->hash);

            return decryptCertData($hashKey, $this->certificate, $this->password, true);
        } catch (\Throwable $th) {
            Log::error('Parse certificate: '.$th->getMessage());
        }

        return null;
    }
```

Table migration:
```
Schema::create('user_certificates', function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->string('name');
            //$table->unsignedInteger('user_id');
            $table->uuid('user_id');
            $table->binary('certificate');
            $table->string('password');
            $table->string('hash');

            $table->timestamps();
        });
```

Error:
```
Process runtime error, reason: "8213037376:error:0DFFF0A8:asn1 encoding routines:CRYPTO_internal:wrong tag:/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/asn1/tasn_dec.c:1167:. 8213037376:error:0DFFF03A:asn1 encoding routines:CRYPTO_internal:nested asn1 error:/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/asn1/tasn_dec.c:337:Type=PKCS12. "
```

**Expected behavior**
That the certificate was retrieved from the DB.

**Screenshots**

**Versions involved:**
- Laravel: [e.g. 10.1.15]
- Laravel A1 Pdf Sign [e.g. 1.0.7]
- Composer [e.g. 2.5.3]
- php 8.1.15

**Additional context**
Running on MacBook Pro M1 Max
MacOS 13.2.1 (22D68)
Laravel Valet

**Comment by lsnepomuceno** [comment]
Hello @rabol,

This issue is probably environment related.

We tried to capture the same error several times and failed.

However, we added more detailed tests on the data stored in the database, I will also include the MacOs environment in the test pipeline to identify possible problems.
