### ISSUE TITLE
setImage() does not work unless you set setSealImgOnEveryPages()

### ISSUE THREAD

**Issue by rabol** [lsnepomuceno/laravel-a1-pdf-sign#92]
**Describe the bug**
adding image via  setImage() like this
```
$resource = $pdf->setImage($imagePath) // USE THE "setImage" METHOD
                            ->signature();
```

does not work

**To Reproduce**
use the code from the documentation: https://laravel-a1-pdf-sign.netlify.app/docs/1.x/sign-pdf-file

**Expected behavior**
That the seal image is added.

**Screenshots**

**Versions involved:**
- Laravel: [e.g. 10.2.0]
- Laravel A1 Pdf Sign [e.g. 1.0.7]
- Composer [e.g. 2.5.3]

**Additional context**

The default parameters for setImage() is specifying the page where the image should be inserted as -1

```
public function setImage(
        string $imagePath,
        float  $pageX = 155,
        float  $pageY = 250,
        float  $imageW = 50,
        float  $imageH = 0,
        int    $page = -1
    ): SignaturePdf
    {
        $this->image = compact('imagePath', 'pageX', 'pageY', 'imageW', 'imageH', 'page');
        return $this;
    }
```
the signature() method that handle insertion of the image have this code:

```
if ($this->hasSealImgOnEveryPages ||
                $i === ($this->image['page'] ?? 0)) {
                $this->implementSignatureImage($i);
            }
```

and since the page property is set to -1, images will only be set when ```$this->hasSealImgOnEveryPages```is ```true```

**Comment by lsnepomuceno** [comment]
Hello @rabol ,

In the last version, I corrected the problem of inserting an image on the defined page and this ended up bringing a side effect where the image on the last page was not inserted.

In [PR93](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/pull/93) I correct this problem, if the default value -1 is used, the signature image will be included in the last page.

I will release the next version in a few hours.

**Comment by rabol** [comment]
Hi

Thanks - any eta on the release ?
